### ISSUE TITLE
Board Selection

### ISSUE THREAD

**Issue by OmriRaz** [OmriRaz/uLab-system-builder#5]
Add a board selection dropdown menu for selecting between Kiwi / Kiwi Lite. @NirGefen

**Comment by NirGefen** [comment]
Done. There is now:
- A main window that lets you choose between the boards.
- The Kiwi window has a "Back" button to return to the boards selection menu

Contact me about the details of the Kiwi Lite window @OmriRaz

**Comment by OmriRaz** [comment]
Looks good @NirGefen 


         .```.   _.''..
        ;     ```      ``'.
        :  d               `.
        / >,:                \
       /.'   `'.,             :
      /'         ;.   .       ;
     /          ;  \ ;     ; /
                `..;\:     :'
               __||   `...,'
              `-,  )   ||
               /.^/ ___||
                   '---,_\   
                      (/ `\

(It's a Kiwi)
